# Generated by Django 5.2.7 on 2026-01-28 13:44

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('icon', models.CharField(default='📚', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Academic Highlight',
                'verbose_name_plural': 'Academic Highlights',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Welcome to Our School', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='Empowering Minds, Shaping Futures')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.hero_upload_path)),
                ('cta_text', models.CharField(default='Admissions Open', max_length=50)),
                ('cta_link', models.CharField(default='/admissions', max_length=255)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='HomeAboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='About Us', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.about_upload_path)),
                ('established_year', models.PositiveIntegerField(default=2000)),
                ('students_count', models.CharField(default='500+', max_length=50)),
                ('teachers_count', models.CharField(default='30+', max_length=50)),
            ],
            options={
                'verbose_name': 'About Section (Home)',
                'verbose_name_plural': 'About Section (Home)',
            },
        ),
    ]
