# Generated by Django 5.2.7 on 2025-12-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='school_motto',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
