# Generated by Django 5.2.7 on 2025-12-20 18:02

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_sitesettings_footer_text_sitesettings_school_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicspage',
            name='calendar_file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.academics_upload_path),
        ),
        migrations.AddField(
            model_name='academicspage',
            name='calendar_title',
            field=models.CharField(default='Academic Calendar', max_length=255),
        ),
        migrations.AddField(
            model_name='academicspage',
            name='curriculum_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='academicspage',
            name='curriculum_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.academics_upload_path),
        ),
        migrations.AddField(
            model_name='academicspage',
            name='curriculum_title',
            field=models.CharField(default='Our Curriculum', max_length=255),
        ),
    ]
