# Generated by Django 5.2.7 on 2025-12-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_academicspage_calendar_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='category',
            field=models.CharField(choices=[('circular', 'Circular'), ('prospectus', 'Prospectus'), ('calendar', 'Academic Calendar'), ('result', 'Results'), ('form', 'Forms'), ('syllabus', 'Syllabus'), ('timetable', 'Timetable'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
