# Generated by Django 5.2.7 on 2025-12-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_download_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_image',
        ),
    ]
