# Generated by Django 5.2.7 on 2025-12-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_aboutpage_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='category',
        ),
        migrations.AddField(
            model_name='classcategory',
            name='classes_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='categories',
            field=models.ManyToManyField(related_name='subjects', to='content.classcategory'),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
