# Generated by Django 5.2.7 on 2025-12-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_subject_category_classcategory_classes_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
