# Generated by Django 5.2.7 on 2025-12-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_classcategory_is_active_subject_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='school_hours',
            field=models.TextField(blank=True),
        ),
    ]
