# Generated by Django 5.2.7 on 2025-12-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_contactpage_school_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_link',
            field=models.URLField(blank=True, default='', help_text='Link to Google Maps location'),
        ),
    ]
