# Generated by Django 5.2.7 on 2025-12-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_sitesettings_google_maps_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='school_phone',
            field=models.TextField(blank=True, default='', help_text='Enter multiple phone numbers separated by commas or newlines'),
        ),
    ]
