# Generated by Django 6.0 on 2026-01-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_sitesettings_school_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Download',
        ),
    ]
