# Generated by Django 5.2.7 on 2026-01-26 06:02
# Manually add slug field using raw SQL to avoid Django's deferred SQL issues

from django.db import migrations, models
from django.utils.text import slugify


def add_slug_column_and_populate(apps, schema_editor):
    """Add slug column and populate for existing notices using raw SQL."""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Add the slug column if it doesn't exist
        cursor.execute('''
            ALTER TABLE content_notice 
            ADD COLUMN IF NOT EXISTS slug VARCHAR(300) DEFAULT '';
        ''')
        
        # Get all existing notices
        cursor.execute('SELECT id, title FROM content_notice;')
        notices = cursor.fetchall()
        
        # Track used slugs
        used_slugs = set()
        
        for notice_id, title in notices:
            base_slug = slugify(title) if title else ''
            if not base_slug:
                base_slug = f"notice-{notice_id}"
            
            slug = base_slug
            counter = 1
            while slug in used_slugs:
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            used_slugs.add(slug)
            
            cursor.execute(
                'UPDATE content_notice SET slug = %s WHERE id = %s;',
                [slug, notice_id]
            )
        
        # Add unique constraint
        cursor.execute('''
            ALTER TABLE content_notice 
            ADD CONSTRAINT content_notice_slug_key UNIQUE (slug);
        ''')
        # Add index for LIKE queries (PostgreSQL varchar_pattern_ops)
        cursor.execute('''
            CREATE INDEX IF NOT EXISTS content_notice_slug_1292d238_like 
            ON content_notice (slug varchar_pattern_ops);
        ''')


def remove_slug_column(apps, schema_editor):
    """Remove slug column."""
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute('DROP INDEX IF EXISTS content_notice_slug_1292d238_like;')
        cursor.execute('ALTER TABLE content_notice DROP CONSTRAINT IF EXISTS content_notice_slug_key;')
        cursor.execute('ALTER TABLE content_notice DROP COLUMN IF EXISTS slug;')


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_delete_download'),
    ]

    operations = [
        migrations.RunPython(add_slug_column_and_populate, remove_slug_column),
        # This SeparateDatabaseAndState tells Django the field exists without trying to create it
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='notice',
                    name='slug',
                    field=models.SlugField(blank=True, max_length=300, unique=True),
                ),
            ],
            database_operations=[],  # Already done in RunPython
        ),
    ]
