# Generated by Django 5.2.7 on 2026-01-26 06:40

from django.db import migrations, models
from django.utils.text import slugify


def ensure_unique_slugs(apps, schema_editor):
    """Ensure all facility slugs are unique before adding constraint."""
    Facility = apps.get_model('content', 'Facility')
    
    # Get all facilities ordered by ID to process older ones first
    facilities = Facility.objects.all().order_by('id')
    
    seen_slugs = set()
    
    for facility in facilities:
        original_slug = facility.slug
        if not original_slug:
            # Generate slug if missing
            original_slug = slugify(facility.name) or f"facility-{facility.id}"
            
        slug = original_slug
        counter = 1
        
        # Check against local set (what we've seen in this loop) and DB
        # Note: Logic here is to fix duplicates within the dataset
        while slug in seen_slugs:
            slug = f"{original_slug}-{counter}"
            counter += 1
            
        seen_slugs.add(slug)
        
        if slug != facility.slug:
            facility.slug = slug
            facility.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_add_slug_to_notice'),
    ]

    operations = [
        # Step 1: Ensure uniqueness for existing data
        migrations.RunPython(ensure_unique_slugs, migrations.RunPython.noop),
        # Step 2: Add unique constraint
        migrations.AlterField(
            model_name='facility',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
