# Generated by Django 5.2.7 on 2026-01-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_facility_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='school_description',
            field=models.TextField(blank=True, default='Committed to providing quality education and nurturing future leaders since establishment.', help_text='Short description displayed in footer below motto'),
        ),
    ]
