# Generated by Django 5.2.7 on 2026-01-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_sitesettings_school_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='office_hours',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='school_hours',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='office_hours',
            field=models.TextField(blank=True, default='', help_text='Office hours (JSON or plain text)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='school_hours',
            field=models.TextField(blank=True, default='', help_text='School hours (JSON or plain text)'),
        ),
    ]
