# Generated by Django 5.2.7 on 2026-01-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fees',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resultsacademics',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
