# Generated by Django 5.2.7 on 2026-01-29 23:01

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_info', '0002_alter_documentation_title_alter_fees_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.core.utils.documentation_upload_path),
        ),
        migrations.AlterField(
            model_name='resultsacademics',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.core.utils.results_upload_path),
        ),
    ]
