# Generated by Django 5.2.7 on 2026-01-28 13:44

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_title', models.CharField(default='Academics', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.academics_upload_path)),
                ('overview_title', models.CharField(default='Academic Excellence', max_length=255)),
                ('overview_content', models.TextField(blank=True)),
                ('curriculum_title', models.CharField(default='Our Curriculum', max_length=255)),
                ('curriculum_content', models.TextField(blank=True)),
                ('curriculum_image', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.academics_upload_path)),
                ('methodology_title', models.CharField(default='Our Teaching Methodology', max_length=255)),
                ('methodology_content', models.TextField(blank=True)),
                ('calendar_title', models.CharField(default='Academic Calendar', max_length=255)),
                ('calendar_file', models.FileField(blank=True, null=True, upload_to=apps.core.utils.academics_upload_path)),
            ],
            options={
                'verbose_name': 'Academics Page',
                'verbose_name_plural': 'Academics Page',
            },
        ),
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('classes_range', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.academics_upload_path)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Class Category',
                'verbose_name_plural': 'Class Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_core', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(related_name='subjects', to='academics.classcategory')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['order', 'name'],
            },
        ),
    ]
