# Generated by Django 5.2.7 on 2026-01-28 13:44

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_open', models.BooleanField(default=True)),
                ('hero_title', models.CharField(default='Admissions', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.admissions_upload_path)),
                ('overview_title', models.CharField(default='Admission Process', max_length=255)),
                ('overview_content', models.TextField(blank=True)),
                ('eligibility_title', models.CharField(default='Eligibility Criteria', max_length=255)),
                ('eligibility_content', models.TextField(blank=True)),
                ('documents_required', models.TextField(blank=True, help_text='One document per line')),
                ('contact_info', models.TextField(blank=True)),
                ('application_form_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Admission Settings',
                'verbose_name_plural': 'Admission Settings',
            },
        ),
        migrations.CreateModel(
            name='AdmissionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='📝', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Admission Step',
                'verbose_name_plural': 'Admission Steps',
                'ordering': ['order'],
            },
        ),
    ]
